// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rpc_service.proto
#ifndef GRPC_rpc_5fservice_2eproto__INCLUDED
#define GRPC_rpc_5fservice_2eproto__INCLUDED

#include "rpc_service.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace adaptive_system {

class SystemControl final {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status retrieveTuple(::grpc::ClientContext* context, const ::adaptive_system::Empty& request, ::adaptive_system::TuplePaLrItv* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::adaptive_system::TuplePaLrItv>> AsyncretrieveTuple(::grpc::ClientContext* context, const ::adaptive_system::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::adaptive_system::TuplePaLrItv>>(AsyncretrieveTupleRaw(context, request, cq));
    }
    virtual ::grpc::Status sendGradient(::grpc::ClientContext* context, const ::adaptive_system::GradientAndLoss& request, ::adaptive_system::Gradient* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::adaptive_system::Gradient>> AsyncsendGradient(::grpc::ClientContext* context, const ::adaptive_system::GradientAndLoss& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::adaptive_system::Gradient>>(AsyncsendGradientRaw(context, request, cq));
    }
    virtual ::grpc::Status sendState(::grpc::ClientContext* context, const ::adaptive_system::PartialStateAndLoss& request, ::adaptive_system::QuantizationLevel* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::adaptive_system::QuantizationLevel>> AsyncsendState(::grpc::ClientContext* context, const ::adaptive_system::PartialStateAndLoss& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::adaptive_system::QuantizationLevel>>(AsyncsendStateRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::adaptive_system::TuplePaLrItv>* AsyncretrieveTupleRaw(::grpc::ClientContext* context, const ::adaptive_system::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::adaptive_system::Gradient>* AsyncsendGradientRaw(::grpc::ClientContext* context, const ::adaptive_system::GradientAndLoss& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::adaptive_system::QuantizationLevel>* AsyncsendStateRaw(::grpc::ClientContext* context, const ::adaptive_system::PartialStateAndLoss& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status retrieveTuple(::grpc::ClientContext* context, const ::adaptive_system::Empty& request, ::adaptive_system::TuplePaLrItv* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::adaptive_system::TuplePaLrItv>> AsyncretrieveTuple(::grpc::ClientContext* context, const ::adaptive_system::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::adaptive_system::TuplePaLrItv>>(AsyncretrieveTupleRaw(context, request, cq));
    }
    ::grpc::Status sendGradient(::grpc::ClientContext* context, const ::adaptive_system::GradientAndLoss& request, ::adaptive_system::Gradient* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::adaptive_system::Gradient>> AsyncsendGradient(::grpc::ClientContext* context, const ::adaptive_system::GradientAndLoss& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::adaptive_system::Gradient>>(AsyncsendGradientRaw(context, request, cq));
    }
    ::grpc::Status sendState(::grpc::ClientContext* context, const ::adaptive_system::PartialStateAndLoss& request, ::adaptive_system::QuantizationLevel* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::adaptive_system::QuantizationLevel>> AsyncsendState(::grpc::ClientContext* context, const ::adaptive_system::PartialStateAndLoss& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::adaptive_system::QuantizationLevel>>(AsyncsendStateRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::adaptive_system::TuplePaLrItv>* AsyncretrieveTupleRaw(::grpc::ClientContext* context, const ::adaptive_system::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::adaptive_system::Gradient>* AsyncsendGradientRaw(::grpc::ClientContext* context, const ::adaptive_system::GradientAndLoss& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::adaptive_system::QuantizationLevel>* AsyncsendStateRaw(::grpc::ClientContext* context, const ::adaptive_system::PartialStateAndLoss& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::RpcMethod rpcmethod_retrieveTuple_;
    const ::grpc::RpcMethod rpcmethod_sendGradient_;
    const ::grpc::RpcMethod rpcmethod_sendState_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status retrieveTuple(::grpc::ServerContext* context, const ::adaptive_system::Empty* request, ::adaptive_system::TuplePaLrItv* response);
    virtual ::grpc::Status sendGradient(::grpc::ServerContext* context, const ::adaptive_system::GradientAndLoss* request, ::adaptive_system::Gradient* response);
    virtual ::grpc::Status sendState(::grpc::ServerContext* context, const ::adaptive_system::PartialStateAndLoss* request, ::adaptive_system::QuantizationLevel* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_retrieveTuple : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_retrieveTuple() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_retrieveTuple() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status retrieveTuple(::grpc::ServerContext* context, const ::adaptive_system::Empty* request, ::adaptive_system::TuplePaLrItv* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestretrieveTuple(::grpc::ServerContext* context, ::adaptive_system::Empty* request, ::grpc::ServerAsyncResponseWriter< ::adaptive_system::TuplePaLrItv>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_sendGradient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_sendGradient() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_sendGradient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendGradient(::grpc::ServerContext* context, const ::adaptive_system::GradientAndLoss* request, ::adaptive_system::Gradient* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsendGradient(::grpc::ServerContext* context, ::adaptive_system::GradientAndLoss* request, ::grpc::ServerAsyncResponseWriter< ::adaptive_system::Gradient>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_sendState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_sendState() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_sendState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendState(::grpc::ServerContext* context, const ::adaptive_system::PartialStateAndLoss* request, ::adaptive_system::QuantizationLevel* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsendState(::grpc::ServerContext* context, ::adaptive_system::PartialStateAndLoss* request, ::grpc::ServerAsyncResponseWriter< ::adaptive_system::QuantizationLevel>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_retrieveTuple<WithAsyncMethod_sendGradient<WithAsyncMethod_sendState<Service > > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_retrieveTuple : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_retrieveTuple() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_retrieveTuple() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status retrieveTuple(::grpc::ServerContext* context, const ::adaptive_system::Empty* request, ::adaptive_system::TuplePaLrItv* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_sendGradient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_sendGradient() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_sendGradient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendGradient(::grpc::ServerContext* context, const ::adaptive_system::GradientAndLoss* request, ::adaptive_system::Gradient* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_sendState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_sendState() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_sendState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendState(::grpc::ServerContext* context, const ::adaptive_system::PartialStateAndLoss* request, ::adaptive_system::QuantizationLevel* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_retrieveTuple : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_retrieveTuple() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::StreamedUnaryHandler< ::adaptive_system::Empty, ::adaptive_system::TuplePaLrItv>(std::bind(&WithStreamedUnaryMethod_retrieveTuple<BaseClass>::StreamedretrieveTuple, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_retrieveTuple() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status retrieveTuple(::grpc::ServerContext* context, const ::adaptive_system::Empty* request, ::adaptive_system::TuplePaLrItv* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedretrieveTuple(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::adaptive_system::Empty,::adaptive_system::TuplePaLrItv>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_sendGradient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_sendGradient() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::StreamedUnaryHandler< ::adaptive_system::GradientAndLoss, ::adaptive_system::Gradient>(std::bind(&WithStreamedUnaryMethod_sendGradient<BaseClass>::StreamedsendGradient, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_sendGradient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status sendGradient(::grpc::ServerContext* context, const ::adaptive_system::GradientAndLoss* request, ::adaptive_system::Gradient* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedsendGradient(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::adaptive_system::GradientAndLoss,::adaptive_system::Gradient>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_sendState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_sendState() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::StreamedUnaryHandler< ::adaptive_system::PartialStateAndLoss, ::adaptive_system::QuantizationLevel>(std::bind(&WithStreamedUnaryMethod_sendState<BaseClass>::StreamedsendState, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_sendState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status sendState(::grpc::ServerContext* context, const ::adaptive_system::PartialStateAndLoss* request, ::adaptive_system::QuantizationLevel* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedsendState(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::adaptive_system::PartialStateAndLoss,::adaptive_system::QuantizationLevel>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_retrieveTuple<WithStreamedUnaryMethod_sendGradient<WithStreamedUnaryMethod_sendState<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_retrieveTuple<WithStreamedUnaryMethod_sendGradient<WithStreamedUnaryMethod_sendState<Service > > > StreamedService;
};

}  // namespace adaptive_system


#endif  // GRPC_rpc_5fservice_2eproto__INCLUDED
